[package]
name = "steelsight"
version = "0.1.0"
authors = ["damast93 <damast93@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
